# Generated by Django 3.2 on 2021-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('Contacto', models.CharField(blank=True, max_length=30)),
                ('morada', models.CharField(max_length=200)),
                ('comprovativo', models.FileField(blank=True, upload_to='uploads/')),
            ],
        ),
    ]
