# Generated by Django 3.2 on 2021-05-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='Contacto',
            new_name='contacto',
        ),
    ]
