# Generated by Django 3.2 on 2021-05-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_contacto_rate_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
