# Generated by Django 3.2 on 2021-04-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='level',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='course',
            new_name='nivel',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='preço',
        ),
        migrations.AddField(
            model_name='service',
            name='duração',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
