# Generated by Django 3.2 on 2021-04-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_charge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charge',
        ),
    ]
